### ISSUE TITLE
Reset option not working

### ISSUE THREAD

**Issue by adisalat2** [rparkins999/CalendarTrigger#11]
Information
.Repository
https://github.com/rparkins999/CalendarTrigger

Project Name: Calendar Trigger

Expected Behaviour
When reset option is click under debugging section,the settings should be resets 

Actual Behaviour 
When reset is click on ,it does not have effect in the application

How to reproduce
Download and install from fdroid 
Run the app
Select three dots on the right side and then select debugging
Click Reset

.Browser:Calendar Trigger v2.0
.Operating System: Android 7.0

Recording of the bug
https://youtu.be/FvSZh1PTkgE

**Comment by rparkins999** [comment]
I think that you have misunderstood what "Reset" is supposed to do. The help information (long click on the button) says:-

This button forces all classes to be inactive and stops all temporary waits. It is for use if the application gets stuck or if you have deleted a calendar event while it was active. Note that if you are between the start and finish times of a calendar event, any  class(es) to which that event belongs will immediately become active again.

I believe that "Reset" does behave as described. If you believe that it doesn't, please provide a more specific description of behaviour that conflicts with this description.
