### ISSUE TITLE
Save settings is not responding

### ISSUE THREAD

**Issue by julimaster** [rparkins999/CalendarTrigger#12]
#### Expected behavior
After clicking on  **Save Settings** Option it  should save, as its expected.

#### Actual behavior
After clicking on save setting it Does not have any effect on the app.

#### How to reproduce
1. Open the app
2. Click on the menu at the right corner of the app.
3. Then click debugging
4.  Click on save setting, it has no effect on the app ,its not responding
5. Bug is visible

***
* Browser/App version: CalendarTrigger version 2.0
* Operating system: Android marshmallow  6.0 ,tecno w3
***
#### Recording Of The Bug
![videotogif_2018.05.28_23.51.18.gif](https://cdn.steemitimages.com/DQmW3j5GSSiNsPQJGrhDqZJMwj3qELq7oCX3T571hWNr4At/videotogif_2018.05.28_23.51.18.gif)

**Comment by rparkins999** [comment]
What behaviour did you expect? It is supposed to write a settings file, and it does that. The Ui might be improved by displaying something acknowledging that it has been done, but this feature is only intended to be used when reinstalling the app, which isn't a normal action.
