### ISSUE TITLE
Matching on multiple strings

### ISSUE THREAD

**Issue by madduck** [rparkins999/CalendarTrigger#17]
Please allow me to match an event class if the title contains "foo OR bar". Or even allow regular expressions...

Thank you!

**Comment by madduck** [comment]
Over in #18, you commented:

> "foo or bar" can be achieved by defining two classes with the same actions. Currently I do in fact ignore All Day events, because they don't have meaningful start and end times, and CalendarTrigger takes action at the starts and ends of events. Excluding "Call or Telco" is much harder to implement, since it effectively requires a fully general SQL WHERE test. This would require a lot of extra User Interface complexity and also increase the battery drain from the app for all users. Given how aggressive Android has become in trying to stop background services draining the battery, I'm reluctant to go down that road. It also complicates the User Interface a lot.
> Incidentally I think that Google are wrong here. If a user wants to run a background service which drains the battery a bit, they should have the choice of doing so. If a rogue app drains the battery a lot without telling the user, most devices will allow the user to find out which app is doing it. In my opinion Google are being overly helpful to device manufacturers who don't put in big enough batteries as opposed to users and app designers who want functionality in the device. CalendarTrigger already has to do a lot of extra work (in fact increasing battery drain) in order to work around Google's limitations.
> If enough users reply to this comment wanting a more general SQL test, I'll think about implementing it when I have time. Of course since it is open source you can always fork it and implement it yourself.

And I understand the reasoning. I would love the feature, and I think there's a middle-ground between the current implementation, and full-featured `SQL WHERE`, but I cannot claim I know how calendar queries work on Android. It seems to be implemented in https://github.com/rparkins999/CalendarTrigger/blob/master/app/src/main/java/uk/co/yahoo/p1rpp/calendartrigger/calendar/CalendarProvider.java .

Does the underlying provider support regular expressions? Because then this would be as easy as reading the field, and if it started and ended with `/`, then treat the contents as a regular expression.

Alternatively, a semi-colon- or comma-separated list would be a good way to implement `OR`.

**Comment by rparkins999** [comment]
"Does the underlying provider support regular expressions?"

It isn't the underlying calendar provider (of which there are usually several) that matters: the interface is an SQL query. Sqlite (the SQL variant used by Android) does not support regular expressions. It does support comparisons negated or **and**ed or **or**ed together, and it does support metacharacters for "any character" or "any string of characters", which is the reason why the string comparisons in CalendarTrigger are "contains". Constructing a Graphical User Interface to create the full generality of a valid SQL query is difficult: even in my [sqlite database editing program for Linux PCs](https://github.com/rparkins999/sqliteman) I can't do it and fall back to letting the user type in their own query if it isn't one of the simple cases that the GUI can generate.

Using a comma-separated list would prevent the user from specifying a matching string containing a comma unless I also supported an escape character. Making these things work properly is harder than it looks.

**Comment by madduck** [comment]
It's true that it's not all that simple, unless you were willing to make some assumptions, such as people not wanting to match on commas. But you are right, defining multiple classes is probably the way to go.

**Comment by rparkins999** [comment]
Version 3.1 will match on FOO or BAR.

**Comment by madduck** [comment]
Thank you!
