### ISSUE TITLE
Suggestion: Add "total silence" mode

### ISSUE THREAD

**Issue by Exaeta** [rparkins999/CalendarTrigger#2]
Total silence is useful, please add it! Prevents accidental media playback while in class etc.

**Comment by rparkins999** [comment]
Total silence is very difficult to do on older androids because there is no master volume control. I'm working on a version which will handle both do not disturb and totally silent modes for Android 6 and later. It will get released when I've made it work properly.

**Comment by rparkins999** [comment]
All Do Not Disturb submodes are now supported in v1.2.0 which I have just released.
