### ISSUE TITLE
Suggestion: Add a notification alarm

### ISSUE THREAD

**Issue by RaSKoR** [rparkins999/CalendarTrigger#3]
Hi,
First thanks for your nice app.

It will be great if we can add a custom notification alarm for specifics events.

I synchronise my calendar with an an remote agenda wich don't provide any notification for his events and I afraid to miss some events that are just display but didn't alert me.

Regards
Emmanuel

**Comment by rparkins999** [comment]
This is in my to-do list. It will happen, but I can't yet say when.

```
  From: RaSKoR <notifications@github.com>
```

 To: rparkins999/CalendarTrigger CalendarTrigger@noreply.github.com 
 Sent: Friday, 4 November 2016, 9:04
 Subject: [rparkins999/CalendarTrigger] Suggestion: Add a notification ring (#3)

Hi,
First thanks for your nice app.It will be great if we can add a custom notification alarm for specifics events.I synchronise my calendar with an an remote agenda wich don't provide any notification for his events and I afraid to miss some events that are just display but didn't alert me.Regards
Emmanuel—

**Comment by rparkins999** [comment]
Version 1.3.0, which I've just pushed, supports notifications with user selectable sounds. I may get round to posting a release soon, but you should be able to build from it now.
